version: '2.1'
services:
  web1:
    build:
      context: ./fakeserver
      dockerfile: Dockerfile
    image: wmyaoyao.pw/fakeserver:latest
    ports:
      - "10081:80"
    environment:
      - PORT=80
      - HOSTNAME=web1
  web2:
    image: wmyaoyao.pw/fakeserver:latest
    ports:
      - "10082:80"
    environment:
      - PORT=80
      - HOSTNAME=web2
  haproxy:
    image: haproxy:1.6-alpine
    ports:
      - "10080:10080"
      - "9527:9527"
    depends_on:
      - "web1"
      - "web2"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
