version: '2'
services:

  redis-master:
    image: redis:4-alpine
    volumes:
      - "./data:/data"
    ports:
      - "6379:6379"

  redis-slave:
    image: redis:4-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    volumes:
      - "./data:/data"
