FROM ubuntu:14.04
MAINTAINER wmyaoyao <wmyaoyao@gmail.com>

# Add an user with sudo access right
RUN useradd -ms /bin/bash devuser
RUN echo "devuser ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers 
USER devuser

WORKDIR /home/devuser
